services:

  #Python Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /app

    ports:
      - "8090:5000"

    volumes:
      - './db-password:/run/secrets/db-password'

    depends_on:
      - db

  #Mariadb
  db:
    image: mariadb:latest
    container_name: db
    restart: 'always'

    command: '--default-authentication-plugin=mysql_native_password'

    environment: 
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: example
